name: Build Executable

on:
  push:
    tags:
      - 'v*'  # Nur ausführen, wenn ein Tag wie v1.0, v1.1 erstellt wird

jobs:
  build-executable:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out code
    - name: Check out code
      uses: actions/checkout@v3

    # 2. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Build executable
    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile main.py
        mv dist/main app-executable  # Rename for clarity

    # 5. Upload the executable as an artifact
    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: flask-app-executable
        path: app-executable
