name: Build and Release Executable

on:
  push:
    tags:
      - "*" # Trigger bei jedem neuen Tag

jobs:
  # 1. Publish Release
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Publish release
      id: publish-release
      uses: ghalactic/github-release-from-tag@v5
      with:
        prerelease: "false"
        reactions: heart,rocket,eyes

  # 2. Build Executable
  executable:
    runs-on: windows-latest
    timeout-minutes: 20
    needs: publish
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create Executable
      uses: sayyid5416/pyinstaller@v1
      with:
        python_ver: '3.12'
        requirements: 'requirements.txt'
        upload_exe_with_name: 'my-flask-app.exe'

    - name: Upload Executable to Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ github.ref_name }} ./dist/my-flask-app.exe --clobber
