name: Build and Deploy to Azure

on:
  push:
    tags:
      - 'v*'  # Nur ausführen, wenn ein Tag wie v1.0, v1.1 erstellt wird

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Code auschecken
    - name: Check out code
      uses: actions/checkout@v3

    # 2. Python-Umgebung einrichten (falls nötig)
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    # 3. Abhängigkeiten installieren
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Docker-Image erstellen (für Azure oder lokal)
    - name: Build Docker image
      run: docker build -t my-flask-app:${{ github.ref_name }} .